#!/bin/bash
apt install -y python3 python-pip # If the package manager of your operating system is not compatible with Apple, you can change this line yum, dnf, pacman, pkg ...
pip install -r ./requirements.txt
